version: 2.1
orbs: 
  slack: circleci/slack@3.4.2 
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Set deployment tag env
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]
            then
              echo "export APP_ENV=staging" >> APP_ENV
            fi
      - run:
          name: Deployment image name env
          command: |
            echo 'export COMMIT_SHORT=$(echo $CIRCLE_SHA1 | cut -c1-7 )' >> IMG_ENV
            echo 'export IMAGE_NAME_ASSETS=$LP_REGISTRY_PATH$CIRCLE_PROJECT_REPONAME-assets:$CIRCLE_BRANCH-$COMMIT_SHORT' >> ASSETS_IMG_ENV
            echo 'export IMAGE_NAME_CARTS=$LP_REGISTRY_PATH$CIRCLE_PROJECT_REPONAME-carts:$CIRCLE_BRANCH-$COMMIT_SHORT' >> CARTS_IMG_ENV
            echo 'export IMAGE_NAME_CATALOG=$LP_REGISTRY_PATH$CIRCLE_PROJECT_REPONAME-catalog:$CIRCLE_BRANCH-$COMMIT_SHORT' >> CATALOG_IMG_ENV
            echo 'export IMAGE_NAME_CHECKOUT=$LP_REGISTRY_PATH$CIRCLE_PROJECT_REPONAME-checkout:$CIRCLE_BRANCH-$COMMIT_SHORT' >> CHECKOUT_IMG_ENV
            echo 'export IMAGE_NAME_ORDERS=$LP_REGISTRY_PATH$CIRCLE_PROJECT_REPONAME-orders:$CIRCLE_BRANCH-$COMMIT_SHORT' >> ORDERS_IMG_ENV
            echo 'export IMAGE_NAME_UI=$LP_REGISTRY_PATH$CIRCLE_PROJECT_REPONAME-ui:$CIRCLE_BRANCH-$COMMIT_SHORT' >> UI_IMG_ENV
            echo -n $LP_REGISTRY_SA | base64 --decode > LP_REGISTRY_SA.json
      - run:
          name: Build docker image for every service
          command: |
            source APP_ENV
            source ASSETS_IMG_ENV
            source CATALOG_IMG_ENV
            source CARTS_IMG_ENV
            source CHECKOUT_IMG_ENV
            source ORDERS_IMG_ENV
            source UI_IMG_ENV

            cd src/assets
            docker build -f Dockerfile --build-arg APP_ENV=$APP_ENV -t $IMAGE_NAME_ASSETS .

            cd ../cart
            docker build -f ../../images/java17/Dockerfile --build-arg APP_ENV=$APP_ENV -t $IMAGE_NAME_CARTS .

            cd ../catalog
            docker build -f ../../images/go/Dockerfile --build-arg APP_ENV=$APP_ENV -t $IMAGE_NAME_CATALOG .

            cd ../checkout
            docker build -f ../../images/nodejs/Dockerfile --build-arg APP_ENV=$APP_ENV -t $IMAGE_NAME_CHECKOUT .

            cd ../orders
            docker build -f ../../images/java17/Dockerfile --build-arg APP_ENV=$APP_ENV -t $IMAGE_NAME_ORDERS .

            cd ../ui
            docker build -f ../../images/java17/Dockerfile --build-arg APP_ENV=$APP_ENV -t $IMAGE_NAME_UI .
      - run: 
          name: Docker push artifact registry
          command: |
            source ASSETS_IMG_ENV
            source CARTS_IMG_ENV
            source CATALOG_IMG_ENV
            source CHECKOUT_IMG_ENV
            source ORDERS_IMG_ENV
            source UI_IMG_ENV
            gcloud auth activate-service-account --key-file LP_REGISTRY_SA.json
            cat LP_REGISTRY_SA.json | docker login -u _json_key --password-stdin https://asia-southeast2-docker.pkg.dev
            gcloud auth configure-docker

            docker push $IMAGE_NAME_ASSETS
            docker push $IMAGE_NAME_CARTS
            docker push $IMAGE_NAME_CATALOG
            docker push $IMAGE_NAME_CHECKOUT
            docker push $IMAGE_NAME_ORDERS
            docker push $IMAGE_NAME_UI

      - run:
          name: Activate service account for GKE
          command: |
            echo -n $GKE_PROJECT_SA | base64 --decode > GKE_PROJECT_SA.json
            export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/GKE_PROJECT_SA.json
            gcloud auth activate-service-account --key-file $(pwd)/GKE_PROJECT_SA.json

      - run:
          name: Update Kubernetes Deployment
          command: |
            source ASSETS_IMG_ENV
            source CATALOG_IMG_ENV
            source CARTS_IMG_ENV
            source CHECKOUT_IMG_ENV
            source ORDERS_IMG_ENV
            source UI_IMG_ENV
            gcloud components install kubectl
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              gcloud container clusters get-credentials gke-infra-cluster --zone asia-southeast1-a --project leftprazz-sgp
              kubectl set image deployment/assets assets=$IMAGE_NAME_ASSETS -n app
              kubectl set image deployment/carts carts=$IMAGE_NAME_CARTS -n app
              kubectl set image deployment/catalog catalog=$IMAGE_NAME_CATALOG -n app
              kubectl set image deployment/checkout checkout=$IMAGE_NAME_CHECKOUT -n app
              kubectl set image deployment/orders orders=$IMAGE_NAME_ORDERS -n app
              kubectl set image deployment/ui ui=$IMAGE_NAME_UI -n app
            fi

      - run: exit 0
      - slack/status: #ci-deployment
          channel: $SLACK_CHANNEL
          failure_message: "Hi $CIRCLE_USERNAME $CIRCLE_PR_USERNAME, Proses $CIRCLE_JOB $CIRCLE_PROJECT_REPONAME Branch $CIRCLE_BRANCH Gagal, Mohon untuk dicek kembali Workflow CInya, Thanks"
          success_message: "Hi $CIRCLE_USERNAME $CIRCLE_PR_USERNAME, Proses $CIRCLE_JOB $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH Berhasil"
          webhook: $WEBHOOK_SLACK

workflows:
  version: 2
  build_and_dockerize:
    jobs:
      - build:
          filters:
            branches:
              only: [ main ]